name: Release

on:
  pull_request: {}
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:  {}

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NUGET_DIR: ${{ github.workspace}}/nuget

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
      - name: Restore .NET Packages
        run: dotnet restore

      - name: Determine Version
        if:  ${{ github.event_name == 'release'  && github.ref_type == 'tag' || github.event.release.tag_name }}
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          updateAssemblyInfo: true

      - name: Build .NET Solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack .NET Solution
        run: dotnet pack --configuration Release --no-build --output pack/
        if:  ${{ github.event_name == 'release'  && github.ref_type == 'tag' || github.event.release.tag_name }}

      - name: Publish .NET Solution to GitHub Packages
        continue-on-error: true
        run: dotnet nuget push pack/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        if:  ${{ github.event_name == 'release'  && github.ref_type == 'tag' || github.event.release.tag_name }}

      - name: Publish .NET Solution to NuGet.org
        env:
          apikey: ${{ secrets.NUGET_ORG_KEY }}
        if:  ${{ github.event_name == 'release'  && github.ref_type == 'tag' || github.event.release.tag_name }}
        run: dotnet nuget push pack/*.nupkg --api-key ${{ secrets.NUGET_ORG_KEY }} --source nuget
        continue-on-error: true
